-   repo: https://github.com/pre-commit/pre-commit-hooks
    sha: v0.7.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: requirements-txt-fixer
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    sha: v0.52.0
    hooks:
    -   id: scss-lint
        language_version: 2.1.5
