repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-yaml
    -   id: requirements-txt-fixer
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-scss-lint
    rev: v0.59.0
    hooks:
    -   id: scss-lint
